### PR TITLE
Bug 5328: Fix ESI build with libxml2 v2.12.0

### PR DESCRIPTION
**Pull request by bkuhls**
Libxml2Parser.cc:147:40: error: invalid conversion from
    'const xmlError*' to 'xmlErrorPtr' {aka 'xmlError*'} [-fpermissive]

libxml2 recently made xmlGetLastError() return a constant object.

### CODE REVIEW

**Review by rousskov — APPROVED** [review]
Thank you for fixing this build problem!

I have polished the fix to use `auto` instead of guessing the exact type, polished PR title to mention that this change fixes Bug [5328](https://bugs.squid-cache.org/show_bug.cgi?id=5328), and polished PR description to fix [formatting](https://github.com/measurement-factory/anubis/blob/master/README.md#pr-description). Please feel free to adjust further as needed.

**Comment by rousskov** [comment]
OK to test

**Review by kinkie — APPROVED** [review]

**Comment by squidadm** [comment]
queued for backport to v6
