### PR TITLE
Fix build with clang v15.0.6 [-Wdeprecated-non-prototype]

### PR DESCRIPTION
**Pull request by kinkie**
clang v15.0.6 distributed with Fedora Rawhide complains about function
definitions using K&R style:

    lib/snmplib/mib.c:229:1: error: a function definition without a
    prototype is deprecated in all versions of C and is not supported in
    C2x [-Werror,-Wdeprecated-non-prototype]

### CODE REVIEW

File: lib/snmplib/mib.c [hunk 1]
```diff
@@ -226,10 +226,7 @@ parse_subtree(struct snmp_mib_tree *subtree, char *input, oid *output, int *out_
 }
 
 int
```
Comment (rousskov) [inline lib/snmplib/mib.c:228]: Let's not drop a potentially useful comment documenting this function parameter:

```suggestion
/// \param out_len number of subid's in "output"
int
```

File: lib/snmplib/mib.c [hunk 2]
```diff
@@ -260,10 +257,7 @@ int *out_len;       /* number of subid's in "output" */
     return (1);
 }
 
-void
-print_objid(objid, objidlen)
-oid *objid;
-int objidlen;       /* number of subidentifiers */
+void print_objid(oid *objid, int objidlen)
```
Comment (rousskov) [inline lib/snmplib/mib.c:260]: Restoring formatting and lost comment:

```suggestion
/// \param objidlen number of subidentifiers
void
print_objid(oid *objid, int objidlen)
```

File: lib/snmplib/mib.c [hunk 3]
```diff
@@ -274,11 +268,7 @@ int objidlen;       /* number of subidentifiers */
 
 }
 
-void
-sprint_objid(buf, objid, objidlen)
-char *buf;
-oid *objid;
-int objidlen;       /* number of subidentifiers */
+void sprint_objid(char *buf, oid *objid, int objidlen)
```
Comment (rousskov) [inline lib/snmplib/mib.c:271]: Restoring formatting and lost comment:

```suggestion
/// \param objidlen number of subidentifiers
void
sprint_objid(char *buf, oid *objid, int objidlen)
```

File: lib/snmplib/snmp_api.c [hunk 4]
```diff
@@ -102,12 +102,8 @@
...
  * occurs, -1 is returned.  If all goes well, 0 is returned.
  */
-int
-snmp_build(session, pdu, packet, out_length)
-struct snmp_session *session;
-struct snmp_pdu *pdu;
-u_char *packet;
-int *out_length;
+int snmp_build(struct snmp_session *session,
+    struct snmp_pdu *pdu, u_char *packet, int *out_length)
```
Comment (rousskov) [inline lib/snmplib/snmp_api.c:106]: Restoring formatting:

```suggestion
int
snmp_build(struct snmp_session *session, struct snmp_pdu *pdu, u_char *packet, int *out_length)
```

**Review by rousskov — COMMENTED** [review]
Thank you for fixing this.

I polished PR title, primarily to highlight that this is a build-fixing change. I also polished PR description, primarily to fix its formatting. Please review and adjust further as needed.

**Comment by kinkie** [comment]
Works for me. Thanks for the fast response

**Review by rousskov — APPROVED** [review]
