### PR TITLE
Fixed writing clean swap file broken in 4310f8b

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**

### CODE REVIEW

**Comment by eduard-bagdasaryan** [comment]
[Here](http://lists.squid-cache.org/pipermail/squid-users/2018-February/017670.html) is squid-users related discussion.

**Comment by rousskov** [comment]
Jenkins build failed on `d-centos-7`, but the failures are completely unrelated to this (trivial) PR change:

```
src/security/KeyData.cc:57:53: error: 'gnutls_pcert_export_x509' was not declared in this scope
src/security/KeyData.cc:148:50: error: 'gnutls_privkey_export_x509' was not declared in this scope
```

I am _guessing_ that Jenkins build environment itself has changed, possibly exposing a previously unknown GnuTLS support bug introduced by rogue 51e09c0 commit (PR #81). Comparing the old successful PR #81 build [log](https://build.squid-cache.org/job/5-pr-test/304/compiler=gcc,label=d-centos-7/console) with this PR failed build [log](https://build.squid-cache.org/job/5-pr-test/348/compiler=gcc,label=d-centos-7/console), I see a new `-I` preprocessor option added, but I do not know who/what added that option and whether that addition caused the build failure:

```
old: configure: BUILD Tools C++ FLAGS:  -g -O2 -std=c++11
new: configure: BUILD Tools C++ FLAGS:  -I/usr/include/p11-kit-1   -g -O2 -std=c++11
```

@squid-cache/devops, if you know what happened and can easily undo that `d-centos-7` change, please undo (at least for now). @yadij, if this compilation error is legitimate, please fix the bug. All  `d-centos-7` tests will fail until this is resolved.

Meanwhile, I plan to ignore these unrelated failures and merge this trivial PR that fixes a high-impact bug.

**Comment by yadij** [comment]
All of the build nodes have had upgrades a few days go instigated by some recent security issues related to SSH and Ruby which affected Jenkins indirectly.

I am looking into it right now.

**Comment by rousskov** [comment]
> All of the build nodes have had upgrades a few days go instigated by some recent security issues related to SSH and Ruby which affected Jenkins indirectly.

IMHO, build node security should be based primarily on isolation rather than (frequent) updates -- an ideal build node does not communicate with the outside world. Any upgrades should be done by building an updated clone and validating that it passes build tests of major official branches. I do not know how far we are from that ideal, but we should be aiming for it.
