### PR TITLE
Fix ntlm_smb_lm_auth build

### PR DESCRIPTION
**Pull request by gozzy**
It seems that due to recent changes in base64 API ntlm_smb_lm_auth module was broken.

Possibly the bug was introduced in commit 1d11e9b3dcdf026a3fe1e76f4279dfaedaf55073

### CODE REVIEW

**Comment by rousskov** [comment]
@gozzy, if you do not mind, in the PR description, please identify the master commit that broke ntlm_smb_lm_auth module. Tracking commit dependencies helps those that port changes from master to other branches.

What was the broken build error? I am a little surprised it did not show up during development, but perhaps it is compiler-dependent and we do not test the right environment with the right compiler.

@squid-prbot, OK to test.

**Comment by gozzy** [comment]
@rousskov, updated the description.

The error was like this:

`
g++ -DHAVE_CONFIG_H   -I../../../.. -I../../../../include -I../../../../lib -I../../../../src -I../../../../include    -I/usr/include/libxml2  -I/usr/include/libxml2 -Wall -Wpointer-arith -Wwrite-strings -Wcomments -Wshadow -Woverloaded-virtual -Werror -Wno-deprecated-register -pipe -D_REENTRANT -g -O2 -c -o ntlm_smb_lm_auth.o ntlm_smb_lm_auth.cc
ntlm_smb_lm_auth.cc: In function 'const char* make_challenge(char*, char*)':
ntlm_smb_lm_auth.cc:206:99: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]
     size_t blen = base64_encode_update(&ctx, b64buf, len, reinterpret_cast<const uint8_t *>(&chal));
                                                                                                   ^
In file included from ntlm_smb_lm_auth.cc:25:0:
../../../../include/base64.h:92:1: note:   initializing argument 2 of 'size_t base64_encode_update(base64_encode_ctx*, char*, size_t, const uint8_t*)'
 base64_encode_update(struct base64_encode_ctx *ctx,
 ^~~~~~~~~~~~~~~~~~~~
ntlm_smb_lm_auth.cc:207:45: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]
     blen += base64_encode_final(&ctx, b64buf+blen);
                                       ~~~~~~^~~~~
In file included from ntlm_smb_lm_auth.cc:25:0:
../../../../include/base64.h:100:1: note:   initializing argument 2 of 'size_t base64_encode_final(base64_encode_ctx*, char*)'
 base64_encode_final(struct base64_encode_ctx *ctx,
 ^~~~~~~~~~~~~~~~~~~
ntlm_smb_lm_auth.cc:209:12: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'const char*' [-fpermissive]
     return b64buf;
            ^~~~~~
ntlm_smb_lm_auth.cc: In function 'void manage_request()':
ntlm_smb_lm_auth.cc:521:102: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'const char*' [-fpermissive]
         if (!base64_decode_update(&ctx, &dstLen, reinterpret_cast<uint8_t*>(decoded), strlen(buf)-3, reinterpret_cast<const uint8_t*>(buf+3)) ||
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ntlm_smb_lm_auth.cc:25:0:
../../../../include/base64.h:151:1: note:   initializing argument 5 of 'int base64_decode_update(base64_decode_ctx*, size_t*, uint8_t*, size_t, const char*)'
 base64_decode_update(struct base64_decode_ctx *ctx,
 ^~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-deprecated-register' [-Werror]
cc1plus: all warnings being treated as errors
`

**Comment by gozzy** [comment]
gcc version is 7.2.1

**Comment by rousskov** [comment]
What is your Nettle version?

**Comment by gozzy** [comment]
libnettle 3.3.1.

**Comment by rousskov** [comment]
Thank you for all the updates. I do not know enough about this code to do a quick review, but I hope that @yadij will be able to move this fix forward.

**Comment by gozzy** [comment]
I've just tried to build squid with nettle 3.3, 3.4 and without the library - seems to compile without any errors.

Also I've looked into ntlm_fake_auth module that had no compilation problems. Either new gcc is too picky, or it's because ntlm_smb is not built by default.

**Comment by rousskov** [comment]
> I've just tried to build squid with nettle 3.3, 3.4 and without the library - seems to compile without any errors.

The above statement is about patched/fixed Squid, right? Unpatched/official Squid fails to build with nettle 3.3.1 per your earlier [comment](https://github.com/squid-cache/squid/pull/109#issuecomment-352883863), I presume.
