### PR TITLE
MingGW: emulate pipe(2)

### PR DESCRIPTION
**Pull request by kinkie**
The pipe(2) function is not available on Windows,
in favour of a broader _pipe() call.

Wrap it in a macro to maintain the interface

Solves error:
```
DiskThreads/CommIO.cc:
   In static member function 'static void CommIO::Initialize()':
DiskThreads/CommIO.cc:26:9: error:
    'pipe' was not declared in this scope; did you mean '_pipe'?
```

### CODE REVIEW

File: compat/os/mingw.h [hunk 1]
```diff
@@ -46,7 +46,9 @@ fsync(int fd)
 }
 #endif
 
-#define mkdir(p,F) mkdir((p))
+/* importaed from mswindows.h */
+#define mkdir(p, F) ::mkdir((p))
+#define pipe(pipefd) ::_pipe((pipefd), 4096, _O_BINARY)
```
Comment (rousskov) [inline compat/os/mingw.h:51]: As in #2018, when duplicating code, please duplicate code as faithfully as possible (instead of adding a new variation). Please disclose and justify any necessary differences.

**Review by rousskov — CHANGES_REQUESTED** [review]
This PR diff shows bad changes unrelated to this PR and conflicting with recent commit 23d4635a.

File: compat/os/mingw.h [hunk 2]
```diff
@@ -46,7 +46,9 @@ fsync(int fd)
 }
 #endif
 
-#define mkdir(p,F) mkdir((p))
+/* importaed from mswindows.h */
```
Comment (yadij) [inline compat/os/mingw.h:49]: 1) This info only matters if the two need to be kept in sync. Implementation in `mswindows.h` is for a different compiler and may thus expected to be different when that compiler build gets fixed.

2)  If there is a copyright assigned to this implementation. the legal requirement t is to duplicate the relevant copyright blurb and update CREDITS.
  - since you, me and Guido (AFAIK the relevant copyright holders for this code) have all delegated GPLv2, this case is not applicable.

```suggestion
```

That said, I do hope you can replace these `#define` with `inline const` whenever possible.

**Review by yadij — CHANGES_REQUESTED** [review]

File: compat/os/mingw.h (hunk 1 above)
Comment (yadij) [reply compat/os/mingw.h:51]: As a general rule that might be good advice. However, these are portability definitions targeted at specific build environments. As such having differences in the code here are expected and often better - the code varies as the environment needs vary.

**Comment by yadij** [comment]
The `mkdir` change removal was wrong. There is a line there in master branch, just leave it untouched here not removed or altered.

**Comment by kinkie** [comment]
> The `mkdir` change removal was wrong. There is a line there in master branch, just leave it untouched here not removed or altered.

readded mkdir.
Also reworked the patch to apply the pattern I'm using just about everywhere.
pipe() is used rarely enough that defining an xpipe wrapper is a viable solution

File: compat/os/mingw.h (hunk 1 above)
Comment (rousskov) [reply compat/os/mingw.h]: > having differences in the code here are expected

I disagree that introducing differences is _expected_ when duplicating code. In exceptional cases, where differences are indeed necessary, they need to be justified (e.g., explaining why this "environment needs" are different and how that difference requires different code).

In this particular case, I doubt the differences are necessary, and I do not see any justification to introduce them.

File: compat/xpipe.h [hunk 3]
```diff
@@ -0,0 +1,30 @@
+/*
+ * Copyright (C) 1996-2023 The Squid Software Foundation and contributors
+ *
+ * Squid software is distributed under GPLv2+ license and includes
+ * contributions from numerous individuals and organizations.
+ * Please see the COPYING and CONTRIBUTORS files for details.
+ */
+
+#ifndef COMPAT_XPIPE_H
```
Comment (rousskov) [inline compat/xpipe.h:9]: Please use `SQUID_<DIR>_<NAME>_H` pattern for new guards to reduce clash risk and to ease code maintenance.

File: compat/xpipe.cc [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+#endif
+#if HAVE_IO_H
+#include <io.h>
+#endif
+
+int
+xpipe(int pipefd[2])
+{
+    return _pipe(pipefd, 4096, _O_BINARY);
+}
```
Comment (rousskov) [inline compat/xpipe.cc:25]: Why not inline this trivial wrapper, especially when we do inline its non-Windows version?

**Review by rousskov — CHANGES_REQUESTED** [review]
Please fix CI before requesting another round of reviews.

File: compat/xpipe.cc (hunk 4 above)
Comment (kinkie) [reply compat/xpipe.cc:25]: The main reason I have is to keep included headers confined to that one unit.
Second one is consistency with other, more complex, wrappers.
The easiest way would be to use a preprocessor macro, not even an inline function.

File: compat/xpipe.h (hunk 3 above)
Comment (kinkie) [reply compat/xpipe.h]: Right. source-maintenance fixed it for me.

File: compat/xpipe.cc (hunk 4 above)
Comment (yadij) [reply compat/xpipe.cc:25]: Both of the `windows.h` and `io.h` headers are widely needed by Squid, have peculiar prerequisites, and are provided by `compat/os/mingw.h` . They should not need to be included here at all.

Comment (yadij) [reply compat/xpipe.cc:25]: FTR When we/Squid prefix a `libcompat` function name with `x...` like this it means that we are violating the POSIX API to workaround some safety issue with the POSIX required behaviour (eg missing c-string terminators on `str*()` API copies, memory left undefined by `free()`, not coping with `NULL` inputs).

I am highlighting this because `xpipe(int)` as defined here does meet any of those criteria. It is simply mapping the local provided API to the needed POSIX one. This is normal trivial portability and as such the POSIX ABI symbol `int pipe(int [2])` should be used.

**Review by yadij — CHANGES_REQUESTED** [review]
I disagree with putting `pipe` into its own `.cc` unit for now. The whole issue of `os/mingw.h` vs `os/mswindows.h` is a red-herring distraction that as I have pointed out already should not even be a consideration.

File: compat/xpipe.cc (hunk 4 above)
Comment (rousskov) [reply compat/xpipe.cc:25]: > The main reason I have is to keep included system headers confined to that one unit.

Looks like Amos' [comment](https://github.com/squid-cache/squid/pull/2029#discussion_r2008708129) addresses that concern better than current PR code does.

>  Second one is consistency with other, more complex, wrappers.

That consistency argument does not work when half of the two function definitions are inlined!

> The easiest way would be to use a preprocessor macro, not even an inline function.

We should avoid macros where possible, for well-known reasons.

> When we/Squid prefix a libcompat function name with x... like this it means that we are violating the POSIX API to workaround some safety issue with the POSIX required behaviour

FWIW, I disagree that an xfoo() function has to violate POSIX foo() API.

**Comment by kinkie** [comment]
reverted from xpipe to pipe.
It's easy to do it here because windows and mingw do not provide a pipe() API.

This will not work with other functions such as socket(), send(), sendto(), setsockopt() etc, because
Windows API with these names but different signatures.

File: compat/pipe.h [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ * Squid software is distributed under GPLv2+ license and includes
+ * contributions from numerous individuals and organizations.
+ * Please see the COPYING and CONTRIBUTORS files for details.
+ */
+
+#ifndef SQUID_COMPAT_PIPE_H
+#define SQUID_COMPAT_PIPE_H
+
+#if HAVE_UNISTD_H
+#include <unistd.h>
```
Comment (yadij) [inline compat/pipe.h:13]: What is this header included for?
 * MSVC situation: It does not exist.
 * MinGW situation: **if** it is somehow detected, then `windows.h` include will break compile.

File: compat/pipe.h [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+#endif
+
+#if _SQUID_WINDOWS_ || _SQUID_MINGW_
+
+#if HAVE_WINDOWS_H
+#include <windows.h>
+#endif
+#if HAVE_IO_H
+#include <io.h>
```
Comment (yadij) [inline compat/pipe.h:22]: This does not have such a strong need to remove as the others. But `compat/os/mingw.h` already included it. So this `#include` is just redundant code bloat.

File: src/DiskIO/DiskThreads/CommIO.cc [hunk 7]
```diff
@@ -10,6 +10,7 @@
 
 #include "squid.h"
 #include "comm/Loops.h"
+#include "compat/pipe.h"
```
Comment (yadij) [inline src/DiskIO/DiskThreads/CommIO.cc:13]: If you are going to insist on having a whole header file just for `pipe()` definition. It should be included into the `compat/os/mingw.h` and `compat/os/mswindows.h` header files.
At worst, it could go at the end of `compat/compat.h` after the `debug.h` include line.

If you are doing this because of issues the `.c` files have - then wrap this `pipe()` definition with:
```c++
#if defined(__cplusplus)
```

**Review by yadij — DISMISSED** [review]

File: compat/pipe.h [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+#define SQUID_COMPAT_PIPE_H
+
+#if HAVE_UNISTD_H
+#include <unistd.h>
+#endif
+
+#if _SQUID_WINDOWS_ || _SQUID_MINGW_
+
+#if HAVE_WINDOWS_H
+#include <windows.h>
```
[the remark this answers is not in the document]
Comment (kinkie) [reply compat/pipe.h:19]: > @kinkie, FYI: `windows.h` contains code that will emit a fatal compile `#error` if there is **any** code logic defined before its first lines.
> 
> That means:
> 
> * the prior `#include <unistd.h>`
> * all of the `.cc` file includes and side effects from `squid.h`
> * all of the `.cc` file other includes between `squid.h` and `compat/pipe.h`
> 
> ... none of it is permitted to exist above this line in the pre-compiler output.
> The only reason you have been able to build this at all is that `squid.h` and `compat/compat.h` already takes care of those dependencies **globally**.
> This is one of those tricky portability things which make touching code in `compat/` so risky.
> 
> For the third time now: Please remove this `windows.h` include.

Got you, removing it; I had not understood what you meant previously

File: compat/pipe.h (hunk 5 above)
Comment (kinkie) [reply compat/pipe.h:13]: The idea is to have units requiring pipe(2) include compat/pipe.h , regardless of the OS

**Review by rousskov — APPROVED** [review]
I removed unwanted parenthesis (with an explanation) and updated PR description to match current PR code. Please double check and do update metadata whenever you make code changes!

**Review by yadij — COMMENTED** [review]
No objection now. Though I dislike the specific implementation choices made.
