### PR TITLE
Fix OpenSSL build with GCC v15.1.1 [-Wformat-truncation=]

### PR DESCRIPTION
**Pull request by kinkie**
On arm64 Fedora 42:

    src/ssl/crtd_message.cc:132:39: error: '%zd' directive output may be
        truncated writing between 1 and 19 bytes into a region
        of size 10 [-Werror=format-truncation=]
        snprintf(buffer, sizeof(buffer), "%zd", body.length());

### CODE REVIEW

**Review by yadij — APPROVED** [review]

File: src/ssl/crtd_message.cc [hunk 1]
```diff
@@ -128,9 +128,7 @@ void Ssl::CrtdMessage::setCode(std::string const & aCode) { code = aCode; }
 std::string Ssl::CrtdMessage::compose() const
 {
     if (code.empty()) return std::string();
-    char buffer[10];
-    snprintf(buffer, sizeof(buffer), "%zd", body.length());
-    return code + ' ' + buffer + ' ' + body;
+    return code + ' ' + std::to_string(body.length()) + ' ' + body;
```
Comment (rousskov) [inline src/ssl/crtd_message.cc:131]: std::to_string is locale-sensitive and, hence, slow. However, I think this fix is the right step forward because this code is already exposed to various std::string problems, and the correct long-term solution requires complex refactoring (to get rid of std::string).

This comment does not request any PR changes.

**Review by rousskov — APPROVED** [review]
Thank you for fixing this. I fixed PR description and improved PR title.

File: src/ssl/crtd_message.cc (hunk 1 above)
Comment (kinkie) [reply src/ssl/crtd_message.cc:131]: Yes, my thoughts exactly

**Comment by squidadm** [comment]
queued for backport to v7
