### PR TITLE
Fix --with-valgrind-debug build broken by commit 02f5357

### PR DESCRIPTION
**Pull request by rousskov**
error: cbdata_htable was not declared in this scope

### CODE REVIEW

**Review by kinkie — APPROVED** [review]
LGTM
